---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-partners-metrics
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
    name: openshift-partners-metrics
    network.openshift.io/policy-group: monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: isv-operator-app
  namespace: openshift-partners-metrics
spec:
  namespaceSelector:
    matchNames:
      - isv-operator
  selector:
    matchLabels:
      app: myapp
  endpoints:
    - port: web
---
apiVersion: v1
kind: Namespace
metadata:
  name: isv-operator
---
kind: Service
apiVersion: v1
metadata:
  name: myapp
  namespace: isv-operator
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  ports:
  - name: web
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: isv-operator
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: machacekondra/metricsapp
        ports:
        - name: web
          containerPort: 8081
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: isv-operator
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: isv-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
